name: Hello from docker
on:
  push:
    branches: [ 'main' ]
    paths: [ 'hello-world-docker-action/**' ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Running container
          uses: ./hello-world-docker-action
          id: container-action
          with:
            who-to-greet: '@lucas'

        - name: echo
          run: |
            echo "Time ${{ steps.container-action.outputs.time }}"
            
